"""init bank models

Revision ID: 9636e4f13bba
Revises: 4d46878d879d
Create Date: 2026-03-30 14:45:17.891192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9636e4f13bba'
down_revision: Union[str, Sequence[str], None] = '4d46878d879d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'bank_accounts',
        sa.Column('currency_id', sa.String(), nullable=True)
    )

    op.execute("""
        UPDATE bank_accounts
        SET currency_id = currency
    """)

    op.execute("""
        UPDATE bank_accounts
        SET currency_id = 'PEN'
        WHERE currency_id IS NULL
    """)

    op.alter_column('bank_accounts', 'currency_id', nullable=False)

    op.drop_column('bank_accounts', 'currency')

    op.alter_column('users', 'firebase_uid',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('users', 'firebase_uid',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.add_column('bank_accounts', sa.Column(
        'currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('bank_accounts', 'currency_id')
    # ### end Alembic commands ###
