"""add transaction and related tables

Revision ID: a3d33041be19
Revises: c9ddea26b1ae
Create Date: 2026-04-06 17:01:01.853366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d33041be19'
down_revision: Union[str, Sequence[str], None] = 'c9ddea26b1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='category_type_enum'), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=6), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index('ix_categories_user_id', 'categories', ['user_id'])
    op.create_index('ix_categories_type', 'categories', ['type'])
    op.create_table('monthly_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_expense', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_fixed_expense', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_variable_expense', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_user_month_balance')
    )
    op.create_index(op.f('ix_monthly_balances_id'), 'monthly_balances', ['id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_table('account_monthly_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('credit_card_id', sa.Integer(), nullable=True),
    sa.Column('investment_fund_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_inflow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_outflow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['investment_fund_id'], ['investment_funds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_monthly_balances_user_id'), 'account_monthly_balances', ['user_id'], unique=False)
    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='recurring_type_enum'), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency_enum'), nullable=False),
    sa.Column('next_execution_date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('credit_card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transactions_id'), 'recurring_transactions', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='transaction_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=True),
    sa.Column('from_credit_card_id', sa.Integer(), nullable=True),
    sa.Column('from_investment_fund_id', sa.Integer(), nullable=True),
    sa.Column('to_account_id', sa.Integer(), nullable=True),
    sa.Column('to_credit_card_id', sa.Integer(), nullable=True),
    sa.Column('to_investment_fund_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('is_fixed', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['from_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['from_credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['from_investment_fund_id'], ['investment_funds.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['to_credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['to_investment_fund_id'], ['investment_funds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_currency_id'), 'transactions', ['currency_id'], unique=False)
    op.create_index(op.f('ix_transactions_from_account_id'), 'transactions', ['from_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_from_credit_card_id'), 'transactions', ['from_credit_card_id'], unique=False)
    op.create_index(op.f('ix_transactions_from_investment_fund_id'), 'transactions', ['from_investment_fund_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_to_account_id'), 'transactions', ['to_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_to_credit_card_id'), 'transactions', ['to_credit_card_id'], unique=False)
    op.create_index(op.f('ix_transactions_to_investment_fund_id'), 'transactions', ['to_investment_fund_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_bank_entity_id'), 'bank_accounts', ['bank_entity_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_currency_id'), 'bank_accounts', ['currency_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_bank_entities_user_id'), 'bank_entities', ['user_id'], unique=False)
    op.create_index(op.f('ix_credit_cards_currency_id'), 'credit_cards', ['currency_id'], unique=False)
    op.create_index(op.f('ix_credit_cards_id'), 'credit_cards', ['id'], unique=False)
    op.alter_column('currencies', 'flag',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_index(op.f('ix_investment_funds_currency_id'), 'investment_funds', ['currency_id'], unique=False)
    op.create_index(op.f('ix_investment_funds_id'), 'investment_funds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    
    op.drop_index(op.f('ix_investment_funds_id'), table_name='investment_funds')
    op.drop_index(op.f('ix_investment_funds_currency_id'), table_name='investment_funds')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.alter_column('currencies', 'flag',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.drop_index(op.f('ix_credit_cards_id'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_currency_id'), table_name='credit_cards')
    op.drop_index(op.f('ix_bank_entities_user_id'), table_name='bank_entities')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_currency_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_bank_entity_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_to_investment_fund_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_to_credit_card_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_to_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_investment_fund_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_credit_card_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_currency_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_recurring_transactions_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    op.drop_index(op.f('ix_account_monthly_balances_user_id'), table_name='account_monthly_balances')
    op.drop_table('account_monthly_balances')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_monthly_balances_id'), table_name='monthly_balances')
    op.drop_table('monthly_balances')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    
    sa.Enum(name='transaction_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='frequency_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='recurring_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='category_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
